development:
  url: https://gateway.marvel.com/v1/public
  public_key: 5f3ca374aec85caae447eff6ff94fed3
  private_key: f10bc178862ee730c312491f165d4cc36d22d77c
  gateway_url: http://localhost:4000/api/v1
  gateway_enabled: true

test:
  url: https://gateway.marvel.com/v1/public
  public_key: 5f3ca374aec85caae447eff6ff94fed3
  private_key: f10bc178862ee730c312491f165d4cc36d22d77c
  gateway_url: http://localhost:4000/api/v1
  gateway_enabled: true
