module StatusCodes
  HTTP_OK_CODE = 200

  HTTP_BAD_REQUEST_CODE = 400
  HTTP_UNAUTHORIZED_CODE = 401
  HTTP_FORBIDDEN_CODE = 403
  HTTP_NOT_FOUND_CODE = 404
  API_NOT_ALLOWED_CODE = 405
  API_BAD_CREDENTIALS_CODE = 409
  API_REACHED_RATE_LIMIT = 429
end
